use crate::evaluation::{cnap_from_prior_standardized_ap, prior_standardized_ap_from_counts};
use crate::execution::map_init_indexed;
use crate::random::{BOOTSTRAP_DOMAIN, rng_for};
use crate::regime::{
    CanonicalFixedModel, FixedScoreResamplingRegime, ReplicateCounts, ReplicateRng,
};
use crate::support::{standard_error_from_cnaps, supported_cnap_from_cnaps};
use crate::{
    BootstrapOptions, Cnap, Evaluation, ObservedMetrics, Parallelism, ReferencePrevalence,
    SupportedApError, SupportedCnapEstimate,
};

impl Evaluation {
    /// The canonical fixed-model regime for this evaluation.
    ///
    /// A stratified `n`-out-of-`n` bootstrap that preserves both class counts.
    pub fn canonical_regime(&self) -> CanonicalFixedModel<'_> {
        CanonicalFixedModel::new(
            &self.positive_blocks,
            &self.negative_blocks,
            self.threshold_count(),
            self.class_counts(),
        )
    }

    /// Construct supported CNAP under the canonical stratified `n`-out-of-`n`
    /// fixed-model bootstrap.
    ///
    /// # Errors
    ///
    /// Returns an error when the support order exceeds the replicate count or
    /// the requested execution policy cannot be created.
    pub fn supported_cnap(
        &self,
        prevalence: ReferencePrevalence,
        options: BootstrapOptions,
    ) -> Result<SupportedCnapEstimate, SupportedApError> {
        let mut profile = self.supported_cnap_profile(&[prevalence], options)?;
        Ok(profile.remove(0))
    }

    /// Construct supported CNAP at several reference prevalences from one set
    /// of replicates.
    ///
    /// Threshold-block counts do not depend on the reference prevalence, so a
    /// replicate is drawn once and evaluated at every prevalence. The sweep
    /// therefore costs one resampling pass rather than one per value, and
    /// because the replicates are shared the comparison across prevalences is
    /// paired rather than independently noisy.
    ///
    /// Model orderings can reverse across reference prevalences, so a claim
    /// that one model has greater supported performance should state the
    /// prevalence or the range over which the ordering holds.
    ///
    /// # Errors
    ///
    /// Returns an error for an empty prevalence profile, an excessive support
    /// order, or an unavailable execution policy.
    pub fn supported_cnap_profile(
        &self,
        prevalences: &[ReferencePrevalence],
        options: BootstrapOptions,
    ) -> Result<Vec<SupportedCnapEstimate>, SupportedApError> {
        let regime = self.canonical_regime();
        let effects = regime_replicate_effects(
            &regime,
            prevalences,
            options.replicates.get(),
            options.support_order.get(),
            options.seed,
            BOOTSTRAP_DOMAIN,
            options.parallelism,
        )?;
        Ok(effects
            .into_iter()
            .zip(prevalences)
            .map(|(cnaps, &prevalence)| build_estimate(self, prevalence, cnaps, options))
            .collect())
    }

    /// Construct supported CNAP under a caller-supplied regime.
    ///
    /// The observed metrics are still read from this evaluation, so the regime
    /// must describe replication of the same design. Conditional-null
    /// calibration is canonical only, so a custom regime needs a null
    /// generated by the same mechanism before its result sits on a
    /// conditional-chance-to-perfect-separation scale.
    ///
    /// # Errors
    ///
    /// Returns an error when the regime layout is incompatible, a draw fails,
    /// recorded counts violate the regime contract, the profile is empty, the
    /// support order is excessive, or execution setup fails.
    pub fn supported_cnap_with_fixed_score_regime<G>(
        &self,
        regime: &G,
        prevalences: &[ReferencePrevalence],
        options: BootstrapOptions,
    ) -> Result<Vec<SupportedCnapEstimate>, SupportedApError>
    where
        G: FixedScoreResamplingRegime,
    {
        if regime.threshold_count() != self.threshold_count() {
            return Err(SupportedApError::RegimeThresholdCountMismatch {
                evaluation: self.threshold_count(),
                regime: regime.threshold_count(),
            });
        }
        let effects = regime_replicate_effects(
            regime,
            prevalences,
            options.replicates.get(),
            options.support_order.get(),
            options.seed,
            BOOTSTRAP_DOMAIN,
            options.parallelism,
        )?;
        Ok(effects
            .into_iter()
            .zip(prevalences)
            .map(|(cnaps, &prevalence)| build_estimate(self, prevalence, cnaps, options))
            .collect())
    }
}

/// Drive a regime for `replicates` draws and reduce each draw at every
/// prevalence. The outer index is the prevalence, the inner the replicate.
pub(crate) fn regime_replicate_effects<G>(
    regime: &G,
    prevalences: &[ReferencePrevalence],
    replicates: usize,
    support_order: usize,
    seed: u64,
    domain: u64,
    parallelism: Parallelism,
) -> Result<Vec<Vec<Cnap>>, SupportedApError>
where
    G: FixedScoreResamplingRegime,
{
    if prevalences.is_empty() {
        return Err(SupportedApError::EmptyPrevalenceProfile);
    }
    if support_order > replicates {
        return Err(SupportedApError::SupportOrderExceedsSample {
            order: support_order,
            sample_size: replicates,
        });
    }

    let threshold_count = regime.threshold_count();
    let counts = regime.class_counts();
    let width = prevalences.len();

    // One row per replicate, one column per prevalence.
    let rows = map_init_indexed(
        replicates,
        parallelism,
        || {
            (
                regime.new_scratch(),
                ReplicateCounts::new(threshold_count, counts),
            )
        },
        |state, replicate| {
            let (scratch, buffer) = state;
            let mut source = rng_for(seed, domain, 0, replicate);
            let mut rng = ReplicateRng::new(&mut source);
            regime.draw(replicate, &mut rng, scratch, buffer)?;
            buffer.validate()?;
            let mut row = Vec::with_capacity(width);
            for &prevalence in prevalences {
                row.push(cnap_from_counts(buffer, prevalence));
            }
            Ok(row)
        },
    )?;

    let mut columns = vec![Vec::with_capacity(replicates); width];
    for row in rows {
        let row = row?;
        for (column, value) in columns.iter_mut().zip(row) {
            column.push(value);
        }
    }
    Ok(columns)
}

#[inline]
pub(crate) fn cnap_from_counts(buffer: &ReplicateCounts, prevalence: ReferencePrevalence) -> Cnap {
    let ap = prior_standardized_ap_from_counts(
        buffer.positive(),
        buffer.negative(),
        buffer.class_counts(),
        prevalence,
    );
    Cnap::from_value(cnap_from_prior_standardized_ap(ap, prevalence))
}

pub(crate) fn build_estimate(
    evaluation: &Evaluation,
    prevalence: ReferencePrevalence,
    cnaps: Vec<Cnap>,
    options: BootstrapOptions,
) -> SupportedCnapEstimate {
    let prior_standardized_ap = evaluation.prior_standardized_average_precision(prevalence);
    let observed_cnap = evaluation.cnap(prevalence);
    let observed = ObservedMetrics::new(prior_standardized_ap, observed_cnap);
    let supported = supported_cnap_from_cnaps(&cnaps, options.support_order);
    let mean = cnaps.iter().map(|cnap| cnap.value()).sum::<f64>() / cnaps.len() as f64;
    let standard_error = standard_error_from_cnaps(&cnaps, options.support_order);

    SupportedCnapEstimate::new(
        observed,
        supported,
        Cnap::from_value(mean),
        standard_error,
        cnaps,
        evaluation.class_counts(),
        prevalence,
        options.support_order,
    )
}
